- name: Create a folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://172.31.12.47:8080
    user: admin
  loop:
    - CI-Pipelines

- name: Include Multi Branch Pipeline tasks
  ansible.builtin.include_tasks: m-pipelines.yml
  vars:
    COMPONENT: "{{item}}"
  loop:
    - frontend
    - catalogue
    - cart
    - user
    - shipping
    - payment
    - init-container

- name: Include Single Branch Pipeline tasks
  ansible.builtin.include_tasks: s-pipelines.yml
  vars:
    COMPONENT: "{{item}}"
  loop:
    - roboshop-infra
    - roboshop-ansible
    - roboshop-helm-chart





